# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MainWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.5.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGroupBox, QLabel,
    QLineEdit, QMainWindow, QMenuBar, QPushButton,
    QSizePolicy, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(400, 400)
        MainWindow.setMinimumSize(QSize(400, 400))
        MainWindow.setMaximumSize(QSize(400, 400))
        MainWindow.setBaseSize(QSize(400, 400))
        font = QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.setting_box = QGroupBox(self.centralwidget)
        self.setting_box.setObjectName(u"setting_box")
        self.setting_box.setGeometry(QRect(10, 10, 380, 71))
        font1 = QFont()
        font1.setPointSize(11)
        self.setting_box.setFont(font1)
        self.setting_alist_label = QLabel(self.setting_box)
        self.setting_alist_label.setObjectName(u"setting_alist_label")
        self.setting_alist_label.setGeometry(QRect(23, 30, 71, 22))
        self.setting_alist_label.setFont(font)
        self.setting_alist_input = QLineEdit(self.setting_box)
        self.setting_alist_input.setObjectName(u"setting_alist_input")
        self.setting_alist_input.setGeometry(QRect(93, 30, 181, 22))
        self.setting_alist_input.setFont(font)
        self.setting_alist_input.setReadOnly(True)
        self.setting_alist_btn = QPushButton(self.setting_box)
        self.setting_alist_btn.setObjectName(u"setting_alist_btn")
        self.setting_alist_btn.setGeometry(QRect(283, 30, 75, 24))
        self.setting_alist_btn.setFont(font)
        self.console_box = QGroupBox(self.centralwidget)
        self.console_box.setObjectName(u"console_box")
        self.console_box.setGeometry(QRect(10, 90, 380, 171))
        self.console_box.setFont(font1)
        self.console_alist_btn_run = QPushButton(self.console_box)
        self.console_alist_btn_run.setObjectName(u"console_alist_btn_run")
        self.console_alist_btn_run.setEnabled(False)
        self.console_alist_btn_run.setGeometry(QRect(10, 30, 75, 31))
        self.console_alist_status_img = QLabel(self.console_box)
        self.console_alist_status_img.setObjectName(u"console_alist_status_img")
        self.console_alist_status_img.setGeometry(QRect(330, 30, 32, 32))
        self.console_alist_status_img.setAlignment(Qt.AlignCenter)
        self.console_alist_status_label = QLabel(self.console_box)
        self.console_alist_status_label.setObjectName(u"console_alist_status_label")
        self.console_alist_status_label.setGeometry(QRect(280, 35, 41, 22))
        self.console_alist_status_label.setFont(font)
        self.line = QFrame(self.console_box)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(260, 10, 20, 191))
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.console_alist_btn_open = QPushButton(self.console_box)
        self.console_alist_btn_open.setObjectName(u"console_alist_btn_open")
        self.console_alist_btn_open.setEnabled(False)
        self.console_alist_btn_open.setGeometry(QRect(180, 30, 75, 31))
        self.console_alist_btn_stop = QPushButton(self.console_box)
        self.console_alist_btn_stop.setObjectName(u"console_alist_btn_stop")
        self.console_alist_btn_stop.setEnabled(False)
        self.console_alist_btn_stop.setGeometry(QRect(95, 30, 75, 31))
        self.console_alist_btn_admin = QPushButton(self.console_box)
        self.console_alist_btn_admin.setObjectName(u"console_alist_btn_admin")
        self.console_alist_btn_admin.setEnabled(False)
        self.console_alist_btn_admin.setGeometry(QRect(10, 70, 100, 26))
        font2 = QFont()
        font2.setPointSize(9)
        self.console_alist_btn_admin.setFont(font2)
        self.help_box = QGroupBox(self.centralwidget)
        self.help_box.setObjectName(u"help_box")
        self.help_box.setGeometry(QRect(10, 280, 381, 71))
        self.help_box.setFont(font1)
        self.help_document = QPushButton(self.help_box)
        self.help_document.setObjectName(u"help_document")
        self.help_document.setGeometry(QRect(15, 30, 75, 24))
        self.help_document.setFont(font)
        self.help_download = QPushButton(self.help_box)
        self.help_download.setObjectName(u"help_download")
        self.help_download.setGeometry(QRect(105, 30, 75, 24))
        self.help_download.setFont(font)
        self.help_add_storage = QPushButton(self.help_box)
        self.help_add_storage.setObjectName(u"help_add_storage")
        self.help_add_storage.setGeometry(QRect(195, 30, 75, 24))
        self.help_add_storage.setFont(font)
        self.help_webdav = QPushButton(self.help_box)
        self.help_webdav.setObjectName(u"help_webdav")
        self.help_webdav.setGeometry(QRect(285, 30, 75, 24))
        self.help_webdav.setFont(font)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QStatusBar(MainWindow)
        self.statusBar.setObjectName(u"statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QMenuBar(MainWindow)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 400, 23))
        MainWindow.setMenuBar(self.menuBar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"PyAList [YCST]", None))
        self.setting_box.setTitle(QCoreApplication.translate("MainWindow", u"\u8bbe\u7f6e", None))
        self.setting_alist_label.setText(QCoreApplication.translate("MainWindow", u"AList \u8def\u5f84\uff1a", None))
        self.setting_alist_input.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\u8bf7\u9009\u62e9 AList \u7a0b\u5e8f\u8def\u5f84", None))
        self.setting_alist_btn.setText(QCoreApplication.translate("MainWindow", u"\u6d4f\u89c8", None))
        self.console_box.setTitle(QCoreApplication.translate("MainWindow", u"\u63a7\u5236\u53f0", None))
        self.console_alist_btn_run.setText(QCoreApplication.translate("MainWindow", u"\u8fd0\u884c", None))
#if QT_CONFIG(tooltip)
        self.console_alist_status_img.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.console_alist_status_img.setText("")
        self.console_alist_status_label.setText(QCoreApplication.translate("MainWindow", u"\u72b6\u6001\uff1a", None))
        self.console_alist_btn_open.setText(QCoreApplication.translate("MainWindow", u"\u6253\u5f00", None))
        self.console_alist_btn_stop.setText(QCoreApplication.translate("MainWindow", u"\u505c\u6b62", None))
        self.console_alist_btn_admin.setText(QCoreApplication.translate("MainWindow", u"\u67e5\u770b\u9ed8\u8ba4\u7528\u6237", None))
        self.help_box.setTitle(QCoreApplication.translate("MainWindow", u"\u5e2e\u52a9", None))
        self.help_document.setText(QCoreApplication.translate("MainWindow", u"AList \u6587\u6863", None))
        self.help_document.setProperty("url", QCoreApplication.translate("MainWindow", u"https://alist.nn.ci/zh/", None))
        self.help_download.setText(QCoreApplication.translate("MainWindow", u"AList \u4e0b\u8f7d", None))
        self.help_download.setProperty("url", QCoreApplication.translate("MainWindow", u"https://github.com/alist-org/alist/releases", None))
        self.help_add_storage.setText(QCoreApplication.translate("MainWindow", u"\u6dfb\u52a0\u5b58\u50a8", None))
        self.help_add_storage.setProperty("url", QCoreApplication.translate("MainWindow", u"https://alist.nn.ci/zh/guide/drivers/common.html", None))
        self.help_webdav.setText(QCoreApplication.translate("MainWindow", u"WebDAV", None))
        self.help_webdav.setProperty("url", QCoreApplication.translate("MainWindow", u"https://alist.nn.ci/zh/guide/webdav.html", None))
    # retranslateUi

